### ISSUE TITLE
Configure proper logging in Octopus

### ISSUE THREAD

**Issue by aszecowka** [kyma-incubator/octopus#17]
Currently, we log every message on Info Level. Some logs are rather debugging information, examples from `scheduler.go`:
```
Cannot get next test to schedule, max concurrency reached
```
```
No tests to execute right now
```
Setting verbosity of logs is not so trivial task, see discusion here: https://github.com/kubernetes-sigs/controller-runtime/issues/167

**Comment by pbochynski** [comment]
Closed due to inactivity.
