### ISSUE TITLE
Missing pod specs for octopus tests

### ISSUE THREAD

**Issue by Demonsthere** [kyma-incubator/octopus#26]
**Description**

The pod definition generated by octopus is missing/ignoring a vital option in the manifests. A running pod doesn't have the `shareProcessNamespace: true` with, if the tests uses an istio sidecar can break the test. Without the option it is impossible to kill the proxy process after a finished test resulting in a never-ending pod. 

**Expected result**

The pod option is present in the pod definition

**Actual result**

The pod option is missing in the running pod 

**Steps to reproduce**

On a cluster, running tests

```
kubectl get pod -n kyma-system oct-tp-testsuite-all-2019-05-17-08-57-test-core-kubeless-int-0 -o yaml | grep "shareProcessNamespace"
```
This doesn't find anything meaning that the option is not set in the pod spec, however in the code we can see [it is present](https://github.com/kyma-project/kyma/blob/master/resources/core/charts/kubeless/templates/tests/test-kubeless.yaml#L176)

**Troubleshooting**

**Comment by pbochynski** [comment]
Is it still valid? @Demonsthere reopen if it is.
