### ISSUE TITLE
Documentation points to deprecated script.

### ISSUE THREAD

**Issue by dekiel** [kyma-incubator/octopus#40]
Our public documentation under https://kyma-project.io/docs/#details-testing-kyma-tests-execution points to .../installation/scripts/testing.sh as a way to run all test.
>To run all tests, use the testing.sh script located in the /installation/scripts/ directory. Internally, the ClusterTestSuite resource is defined. It fetches all TestDefinitions and executes them."

Whereas script says:
```echo "The testing.sh script is deprecated and will be removed. Use Kyma CLI instead."```

We should update documentation to point to Kyma CLI as a default way of running tests.

**Comment by aszecowka** [comment]
@dekiel why you created this issue in the Octopus repository? It should be rather in kyma repo. Please move it there and close this issue.

**Comment by PK85** [comment]
Closing a ticket. @dekiel please move to kyma repository and contact technical writers
